# Name of workflow
name: development workflow

# When workflow is triggered
on:
  pull_request:
    branches:
      - part_2
      - part_3
      - part_4

# Jobs to carry out
jobs:
  deploy:
    # Operating system to run job on
    runs-on: ubuntu-latest

    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v1
      # Install NodeJS
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      # Run npm install and build on our code
      - run: npm install
      - run: npm run build --if-present
      # Deploy to Netlify using our dev secrets
      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_PART1_ID: ${{ secrets.NETLIFY_PART1_ID }}
          MOVIESDBKEY: ${{ secrets.MOVIESDBKEY }}
        with:
          args: deploy --dir=build --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_PART1_ID", "MOVIESDBKEY"]'
